void c()
{
//=========Macro generated from canvas: c/c
//=========  (Wed Jul 21 16:16:10 2021) by ROOT version 6.18/04
   TCanvas *c = new TCanvas("c", "c",125,57,700,606);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.16);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.16);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.29);
   pad1->Draw();
   pad1->cd();
   pad1->Range(105.679,-2,136.5432,2);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(0);
   pad1->SetGridy();
   pad1->SetLeftMargin(0.14);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0);
   pad1->SetBottomMargin(0.5);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   
   TH1F *h_ratio__1 = new TH1F("h_ratio__1","Mass of four-lepton system",4,110,135);
   h_ratio__1->SetBinContent(0,0.9661757);
   h_ratio__1->SetBinContent(1,1.32442);
   h_ratio__1->SetBinContent(2,1.565133);
   h_ratio__1->SetBinContent(3,1.169315);
   h_ratio__1->SetBinContent(4,1.182801);
   h_ratio__1->SetBinContent(5,0.9690979);
   h_ratio__1->SetBinError(0,0.149591);
   h_ratio__1->SetBinError(1,0.7906329);
   h_ratio__1->SetBinError(2,0.4961173);
   h_ratio__1->SetBinError(3,0.3464353);
   h_ratio__1->SetBinError(4,0.5397193);
   h_ratio__1->SetBinError(5,0.06186683);
   h_ratio__1->SetMinimum(0);
   h_ratio__1->SetMaximum(2);
   h_ratio__1->SetEntries(21.42229);
   h_ratio__1->SetDirectory(0);
   h_ratio__1->SetStats(0);
   h_ratio__1->SetLineWidth(2);
   h_ratio__1->SetMarkerStyle(20);
   h_ratio__1->SetMarkerSize(1.2);
   h_ratio__1->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   h_ratio__1->GetXaxis()->SetLabelFont(42);
   h_ratio__1->GetXaxis()->SetLabelOffset(0.035);
   h_ratio__1->GetXaxis()->SetLabelSize(0.13);
   h_ratio__1->GetXaxis()->SetTitleSize(0.15);
   h_ratio__1->GetXaxis()->SetTitleOffset(1.2);
   h_ratio__1->GetXaxis()->SetTitleFont(42);
   h_ratio__1->GetYaxis()->SetTitle("Data / Pred   ");
   h_ratio__1->GetYaxis()->CenterTitle(true);
   h_ratio__1->GetYaxis()->SetNdivisions(-504);
   h_ratio__1->GetYaxis()->SetLabelFont(42);
   h_ratio__1->GetYaxis()->SetLabelOffset(0.01);
   h_ratio__1->GetYaxis()->SetLabelSize(0.1);
   h_ratio__1->GetYaxis()->SetTitleSize(0.12);
   h_ratio__1->GetYaxis()->SetTitleOffset(0.45);
   h_ratio__1->GetYaxis()->SetTitleFont(42);
   h_ratio__1->GetZaxis()->SetLabelFont(42);
   h_ratio__1->GetZaxis()->SetLabelSize(0.05);
   h_ratio__1->GetZaxis()->SetTitleSize(0.05);
   h_ratio__1->GetZaxis()->SetTitleOffset(1);
   h_ratio__1->GetZaxis()->SetTitleFont(42);
   h_ratio__1->Draw("0E1");
   TLine *line = new TLine(110,1,135,1);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#666666");
   line->SetLineColor(ci);
   line->SetLineWidth(2);
   line->Draw();
   
   TH1F *h_ratio_copy__2 = new TH1F("h_ratio_copy__2","Mass of four-lepton system",4,110,135);
   h_ratio_copy__2->SetBinContent(0,0.9661757);
   h_ratio_copy__2->SetBinContent(1,1.32442);
   h_ratio_copy__2->SetBinContent(2,1.565133);
   h_ratio_copy__2->SetBinContent(3,1.169315);
   h_ratio_copy__2->SetBinContent(4,1.182801);
   h_ratio_copy__2->SetBinContent(5,0.9690979);
   h_ratio_copy__2->SetBinError(0,0.149591);
   h_ratio_copy__2->SetBinError(1,0.7906329);
   h_ratio_copy__2->SetBinError(2,0.4961173);
   h_ratio_copy__2->SetBinError(3,0.3464353);
   h_ratio_copy__2->SetBinError(4,0.5397193);
   h_ratio_copy__2->SetBinError(5,0.06186683);
   h_ratio_copy__2->SetMinimum(0);
   h_ratio_copy__2->SetMaximum(2);
   h_ratio_copy__2->SetEntries(21.42229);
   h_ratio_copy__2->SetDirectory(0);
   h_ratio_copy__2->SetStats(0);
   h_ratio_copy__2->SetLineWidth(2);
   h_ratio_copy__2->SetMarkerStyle(20);
   h_ratio_copy__2->SetMarkerSize(1.2);
   h_ratio_copy__2->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   h_ratio_copy__2->GetXaxis()->SetLabelFont(42);
   h_ratio_copy__2->GetXaxis()->SetLabelOffset(0.035);
   h_ratio_copy__2->GetXaxis()->SetLabelSize(0.13);
   h_ratio_copy__2->GetXaxis()->SetTitleSize(0.15);
   h_ratio_copy__2->GetXaxis()->SetTitleOffset(1.2);
   h_ratio_copy__2->GetXaxis()->SetTitleFont(42);
   h_ratio_copy__2->GetYaxis()->SetTitle("Data / Pred   ");
   h_ratio_copy__2->GetYaxis()->CenterTitle(true);
   h_ratio_copy__2->GetYaxis()->SetNdivisions(-504);
   h_ratio_copy__2->GetYaxis()->SetLabelFont(42);
   h_ratio_copy__2->GetYaxis()->SetLabelOffset(0.01);
   h_ratio_copy__2->GetYaxis()->SetLabelSize(0.1);
   h_ratio_copy__2->GetYaxis()->SetTitleSize(0.12);
   h_ratio_copy__2->GetYaxis()->SetTitleOffset(0.45);
   h_ratio_copy__2->GetYaxis()->SetTitleFont(42);
   h_ratio_copy__2->GetZaxis()->SetLabelFont(42);
   h_ratio_copy__2->GetZaxis()->SetLabelSize(0.05);
   h_ratio_copy__2->GetZaxis()->SetTitleSize(0.05);
   h_ratio_copy__2->GetZaxis()->SetTitleOffset(1);
   h_ratio_copy__2->GetZaxis()->SetTitleFont(42);
   h_ratio_copy__2->Draw("sameaxis");
   
   TH1F *h_ratio__3 = new TH1F("h_ratio__3","Mass of four-lepton system",4,110,135);
   h_ratio__3->SetBinContent(0,0.9661757);
   h_ratio__3->SetBinContent(1,1.32442);
   h_ratio__3->SetBinContent(2,1.565133);
   h_ratio__3->SetBinContent(3,1.169315);
   h_ratio__3->SetBinContent(4,1.182801);
   h_ratio__3->SetBinContent(5,0.9690979);
   h_ratio__3->SetBinError(0,0.149591);
   h_ratio__3->SetBinError(1,0.7906329);
   h_ratio__3->SetBinError(2,0.4961173);
   h_ratio__3->SetBinError(3,0.3464353);
   h_ratio__3->SetBinError(4,0.5397193);
   h_ratio__3->SetBinError(5,0.06186683);
   h_ratio__3->SetMinimum(0);
   h_ratio__3->SetMaximum(2);
   h_ratio__3->SetEntries(21.42229);
   h_ratio__3->SetDirectory(0);
   h_ratio__3->SetStats(0);
   h_ratio__3->SetLineWidth(2);
   h_ratio__3->SetMarkerStyle(20);
   h_ratio__3->SetMarkerSize(1.2);
   h_ratio__3->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   h_ratio__3->GetXaxis()->SetLabelFont(42);
   h_ratio__3->GetXaxis()->SetLabelOffset(0.035);
   h_ratio__3->GetXaxis()->SetLabelSize(0.13);
   h_ratio__3->GetXaxis()->SetTitleSize(0.15);
   h_ratio__3->GetXaxis()->SetTitleOffset(1.2);
   h_ratio__3->GetXaxis()->SetTitleFont(42);
   h_ratio__3->GetYaxis()->SetTitle("Data / Pred   ");
   h_ratio__3->GetYaxis()->CenterTitle(true);
   h_ratio__3->GetYaxis()->SetNdivisions(-504);
   h_ratio__3->GetYaxis()->SetLabelFont(42);
   h_ratio__3->GetYaxis()->SetLabelOffset(0.01);
   h_ratio__3->GetYaxis()->SetLabelSize(0.1);
   h_ratio__3->GetYaxis()->SetTitleSize(0.12);
   h_ratio__3->GetYaxis()->SetTitleOffset(0.45);
   h_ratio__3->GetYaxis()->SetTitleFont(42);
   h_ratio__3->GetZaxis()->SetLabelFont(42);
   h_ratio__3->GetZaxis()->SetLabelSize(0.05);
   h_ratio__3->GetZaxis()->SetTitleSize(0.05);
   h_ratio__3->GetZaxis()->SetTitleOffset(1);
   h_ratio__3->GetZaxis()->SetTitleFont(42);
   h_ratio__3->Draw("SAME0E1");
   
   TH1F *h_ratio__4 = new TH1F("h_ratio__4","Mass of four-lepton system",4,110,135);
   h_ratio__4->SetBinContent(0,0.9661757);
   h_ratio__4->SetBinContent(1,1.32442);
   h_ratio__4->SetBinContent(2,1.565133);
   h_ratio__4->SetBinContent(3,1.169315);
   h_ratio__4->SetBinContent(4,1.182801);
   h_ratio__4->SetBinContent(5,0.9690979);
   h_ratio__4->SetBinError(0,0.149591);
   h_ratio__4->SetBinError(1,0.7906329);
   h_ratio__4->SetBinError(2,0.4961173);
   h_ratio__4->SetBinError(3,0.3464353);
   h_ratio__4->SetBinError(4,0.5397193);
   h_ratio__4->SetBinError(5,0.06186683);
   h_ratio__4->SetMinimum(0);
   h_ratio__4->SetMaximum(2);
   h_ratio__4->SetEntries(21.42229);
   h_ratio__4->SetDirectory(0);
   h_ratio__4->SetStats(0);
   h_ratio__4->SetLineWidth(2);
   h_ratio__4->SetMarkerStyle(20);
   h_ratio__4->SetMarkerSize(1.2);
   h_ratio__4->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   h_ratio__4->GetXaxis()->SetLabelFont(42);
   h_ratio__4->GetXaxis()->SetLabelOffset(0.035);
   h_ratio__4->GetXaxis()->SetLabelSize(0.13);
   h_ratio__4->GetXaxis()->SetTitleSize(0.15);
   h_ratio__4->GetXaxis()->SetTitleOffset(1.2);
   h_ratio__4->GetXaxis()->SetTitleFont(42);
   h_ratio__4->GetYaxis()->SetTitle("Data / Pred   ");
   h_ratio__4->GetYaxis()->CenterTitle(true);
   h_ratio__4->GetYaxis()->SetNdivisions(-504);
   h_ratio__4->GetYaxis()->SetLabelFont(42);
   h_ratio__4->GetYaxis()->SetLabelOffset(0.01);
   h_ratio__4->GetYaxis()->SetLabelSize(0.1);
   h_ratio__4->GetYaxis()->SetTitleSize(0.12);
   h_ratio__4->GetYaxis()->SetTitleOffset(0.45);
   h_ratio__4->GetYaxis()->SetTitleFont(42);
   h_ratio__4->GetZaxis()->SetLabelFont(42);
   h_ratio__4->GetZaxis()->SetLabelSize(0.05);
   h_ratio__4->GetZaxis()->SetTitleSize(0.05);
   h_ratio__4->GetZaxis()->SetTitleOffset(1);
   h_ratio__4->GetZaxis()->SetTitleFont(42);
   h_ratio__4->Draw("SAMEAXIS");
//Primitive: yaxis/Data / Pred   . You must implement TAxis::SavePrimitive
   
   TH1F *h_ratio__5 = new TH1F("h_ratio__5","Mass of four-lepton system",4,110,135);
   h_ratio__5->SetBinContent(0,0.9661757);
   h_ratio__5->SetBinContent(1,1.32442);
   h_ratio__5->SetBinContent(2,1.565133);
   h_ratio__5->SetBinContent(3,1.169315);
   h_ratio__5->SetBinContent(4,1.182801);
   h_ratio__5->SetBinContent(5,0.9690979);
   h_ratio__5->SetBinError(0,0.149591);
   h_ratio__5->SetBinError(1,0.7906329);
   h_ratio__5->SetBinError(2,0.4961173);
   h_ratio__5->SetBinError(3,0.3464353);
   h_ratio__5->SetBinError(4,0.5397193);
   h_ratio__5->SetBinError(5,0.06186683);
   h_ratio__5->SetMinimum(0);
   h_ratio__5->SetMaximum(2);
   h_ratio__5->SetEntries(21.42229);
   h_ratio__5->SetDirectory(0);
   h_ratio__5->SetStats(0);
   h_ratio__5->SetLineWidth(2);
   h_ratio__5->SetMarkerStyle(20);
   h_ratio__5->SetMarkerSize(1.2);
   h_ratio__5->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   h_ratio__5->GetXaxis()->SetLabelFont(42);
   h_ratio__5->GetXaxis()->SetLabelOffset(0.035);
   h_ratio__5->GetXaxis()->SetLabelSize(0.13);
   h_ratio__5->GetXaxis()->SetTitleSize(0.15);
   h_ratio__5->GetXaxis()->SetTitleOffset(1.2);
   h_ratio__5->GetXaxis()->SetTitleFont(42);
   h_ratio__5->GetYaxis()->SetTitle("Data / Pred   ");
   h_ratio__5->GetYaxis()->CenterTitle(true);
   h_ratio__5->GetYaxis()->SetNdivisions(-504);
   h_ratio__5->GetYaxis()->SetLabelFont(42);
   h_ratio__5->GetYaxis()->SetLabelOffset(0.01);
   h_ratio__5->GetYaxis()->SetLabelSize(0.1);
   h_ratio__5->GetYaxis()->SetTitleSize(0.12);
   h_ratio__5->GetYaxis()->SetTitleOffset(0.45);
   h_ratio__5->GetYaxis()->SetTitleFont(42);
   h_ratio__5->GetZaxis()->SetLabelFont(42);
   h_ratio__5->GetZaxis()->SetLabelSize(0.05);
   h_ratio__5->GetZaxis()->SetTitleSize(0.05);
   h_ratio__5->GetZaxis()->SetTitleOffset(1);
   h_ratio__5->GetZaxis()->SetTitleFont(42);
   h_ratio__5->Draw("SAME0E1");
   
   TPaveText *pt = new TPaveText(0.3875645,0.9265101,0.6124355,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Mass of four-lepton system");
   pt->Draw();
   pad1->Modified();
   c->cd();
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.29,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(105.679,0.1,136.5432,37.22766);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(0);
   pad0->SetLeftMargin(0.14);
   pad0->SetRightMargin(0.05);
   pad0->SetTopMargin(0.06);
   pad0->SetBottomMargin(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameBorderMode(0);
   
   TH1F *mass_four_lep__6 = new TH1F("mass_four_lep__6","Mass of four-lepton system",4,110,135);
   mass_four_lep__6->SetBinContent(0,42);
   mass_four_lep__6->SetBinContent(1,3);
   mass_four_lep__6->SetBinContent(2,11);
   mass_four_lep__6->SetBinContent(3,12);
   mass_four_lep__6->SetBinContent(4,5);
   mass_four_lep__6->SetBinContent(5,248);
   mass_four_lep__6->SetMinimum(0.1);
   mass_four_lep__6->SetMaximum(35);
   mass_four_lep__6->SetEntries(321);
   mass_four_lep__6->SetDirectory(0);
   mass_four_lep__6->SetStats(0);
   mass_four_lep__6->SetLineWidth(2);
   mass_four_lep__6->SetMarkerStyle(20);
   mass_four_lep__6->SetMarkerSize(1.2);
   mass_four_lep__6->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   mass_four_lep__6->GetXaxis()->SetLabelFont(42);
   mass_four_lep__6->GetXaxis()->SetLabelSize(0);
   mass_four_lep__6->GetXaxis()->SetTitleSize(0);
   mass_four_lep__6->GetXaxis()->SetTitleOffset(1.4);
   mass_four_lep__6->GetXaxis()->SetTitleFont(42);
   mass_four_lep__6->GetYaxis()->SetTitle("Events / bin");
   mass_four_lep__6->GetYaxis()->SetLabelFont(42);
   mass_four_lep__6->GetYaxis()->SetLabelSize(0.05);
   mass_four_lep__6->GetYaxis()->SetTitleSize(0.05);
   mass_four_lep__6->GetYaxis()->SetTitleOffset(1.2);
   mass_four_lep__6->GetYaxis()->SetTitleFont(42);
   mass_four_lep__6->GetZaxis()->SetLabelFont(42);
   mass_four_lep__6->GetZaxis()->SetLabelSize(0.05);
   mass_four_lep__6->GetZaxis()->SetTitleSize(0.05);
   mass_four_lep__6->GetZaxis()->SetTitleOffset(1);
   mass_four_lep__6->GetZaxis()->SetTitleFont(42);
   mass_four_lep__6->Draw("E1");
   TLatex *   tex = new TLatex(0.18,0.71,"H #rightarrow ZZ* #rightarrow 4l");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.79,"#sqrt{s} = 13 TeV, 10 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *_stack_1 = new TH1F("_stack_1","",4,110,135);
   _stack_1->SetMinimum(-0.5512807);
   _stack_1->SetMaximum(10.77554);
   _stack_1->SetDirectory(0);
   _stack_1->SetStats(0);
   _stack_1->SetLineWidth(2);
   _stack_1->SetMarkerStyle(20);
   _stack_1->SetMarkerSize(1.2);
   _stack_1->GetXaxis()->SetLabelFont(42);
   _stack_1->GetXaxis()->SetLabelSize(0.05);
   _stack_1->GetXaxis()->SetTitleSize(0.05);
   _stack_1->GetXaxis()->SetTitleOffset(1.4);
   _stack_1->GetXaxis()->SetTitleFont(42);
   _stack_1->GetYaxis()->SetLabelFont(42);
   _stack_1->GetYaxis()->SetLabelSize(0.05);
   _stack_1->GetYaxis()->SetTitleSize(0.05);
   _stack_1->GetYaxis()->SetTitleOffset(1.4);
   _stack_1->GetYaxis()->SetTitleFont(42);
   _stack_1->GetZaxis()->SetLabelFont(42);
   _stack_1->GetZaxis()->SetLabelSize(0.05);
   _stack_1->GetZaxis()->SetTitleSize(0.05);
   _stack_1->GetZaxis()->SetTitleOffset(1);
   _stack_1->GetZaxis()->SetTitleFont(42);
   ->SetHistogram(_stack_1);
   
   
   TH1F *mass_four_lep_stack_1 = new TH1F("mass_four_lep_stack_1","Mass of four-lepton system",4,110,135);
   mass_four_lep_stack_1->SetBinContent(0,1.129879);
   mass_four_lep_stack_1->SetBinContent(1,-0.2176677);
   mass_four_lep_stack_1->SetBinContent(2,1.785998);
   mass_four_lep_stack_1->SetBinContent(3,1.460342);
   mass_four_lep_stack_1->SetBinContent(4,0.7207549);
   mass_four_lep_stack_1->SetBinContent(5,7.409811);
   mass_four_lep_stack_1->SetBinError(0,0.4181067);
   mass_four_lep_stack_1->SetBinError(1,0.3336129);
   mass_four_lep_stack_1->SetBinError(2,0.6806289);
   mass_four_lep_stack_1->SetBinError(3,0.673899);
   mass_four_lep_stack_1->SetBinError(4,0.3661171);
   mass_four_lep_stack_1->SetBinError(5,1.270738);
   mass_four_lep_stack_1->SetEntries(705);
   mass_four_lep_stack_1->SetDirectory(0);
   mass_four_lep_stack_1->SetStats(0);

   ci = TColor::GetColor("#6666cc");
   mass_four_lep_stack_1->SetFillColor(ci);
   mass_four_lep_stack_1->SetLineWidth(0);
   mass_four_lep_stack_1->SetMarkerStyle(20);
   mass_four_lep_stack_1->SetMarkerSize(1.2);
   mass_four_lep_stack_1->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   mass_four_lep_stack_1->GetXaxis()->SetLabelFont(42);
   mass_four_lep_stack_1->GetXaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_1->GetXaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_1->GetXaxis()->SetTitleOffset(1.4);
   mass_four_lep_stack_1->GetXaxis()->SetTitleFont(42);
   mass_four_lep_stack_1->GetYaxis()->SetTitle("Events / bin");
   mass_four_lep_stack_1->GetYaxis()->SetLabelFont(42);
   mass_four_lep_stack_1->GetYaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_1->GetYaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_1->GetYaxis()->SetTitleOffset(1.4);
   mass_four_lep_stack_1->GetYaxis()->SetTitleFont(42);
   mass_four_lep_stack_1->GetZaxis()->SetLabelFont(42);
   mass_four_lep_stack_1->GetZaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_1->GetZaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_1->GetZaxis()->SetTitleOffset(1);
   mass_four_lep_stack_1->GetZaxis()->SetTitleFont(42);
   ->Add(mass_four_lep_stack_1,"");
   
   TH1F *mass_four_lep_stack_2 = new TH1F("mass_four_lep_stack_2","Mass of four-lepton system",4,110,135);
   mass_four_lep_stack_2->SetBinContent(0,42.19519);
   mass_four_lep_stack_2->SetBinContent(1,2.202801);
   mass_four_lep_stack_2->SetBinContent(2,2.857178);
   mass_four_lep_stack_2->SetBinContent(3,3.321608);
   mass_four_lep_stack_2->SetBinContent(4,3.318251);
   mass_four_lep_stack_2->SetBinContent(5,248.4775);
   mass_four_lep_stack_2->SetBinError(0,0.3628279);
   mass_four_lep_stack_2->SetBinError(1,0.08289896);
   mass_four_lep_stack_2->SetBinError(2,0.09596057);
   mass_four_lep_stack_2->SetBinError(3,0.1164039);
   mass_four_lep_stack_2->SetBinError(4,0.1129166);
   mass_four_lep_stack_2->SetBinError(5,1.103083);
   mass_four_lep_stack_2->SetEntries(456192);
   mass_four_lep_stack_2->SetDirectory(0);
   mass_four_lep_stack_2->SetStats(0);

   ci = TColor::GetColor("#33ccff");
   mass_four_lep_stack_2->SetFillColor(ci);
   mass_four_lep_stack_2->SetLineWidth(0);
   mass_four_lep_stack_2->SetMarkerStyle(20);
   mass_four_lep_stack_2->SetMarkerSize(1.2);
   mass_four_lep_stack_2->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   mass_four_lep_stack_2->GetXaxis()->SetLabelFont(42);
   mass_four_lep_stack_2->GetXaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_2->GetXaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_2->GetXaxis()->SetTitleOffset(1.4);
   mass_four_lep_stack_2->GetXaxis()->SetTitleFont(42);
   mass_four_lep_stack_2->GetYaxis()->SetTitle("Events / bin");
   mass_four_lep_stack_2->GetYaxis()->SetLabelFont(42);
   mass_four_lep_stack_2->GetYaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_2->GetYaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_2->GetYaxis()->SetTitleOffset(1.4);
   mass_four_lep_stack_2->GetYaxis()->SetTitleFont(42);
   mass_four_lep_stack_2->GetZaxis()->SetLabelFont(42);
   mass_four_lep_stack_2->GetZaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_2->GetZaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_2->GetZaxis()->SetTitleOffset(1);
   mass_four_lep_stack_2->GetZaxis()->SetTitleFont(42);
   ->Add(mass_four_lep_stack_2,"");
   
   TH1F *mass_four_lep_stack_3 = new TH1F("mass_four_lep_stack_3","Mass of four-lepton system",4,110,135);
   mass_four_lep_stack_3->SetBinContent(0,0.1452911);
   mass_four_lep_stack_3->SetBinContent(1,0.2800092);
   mass_four_lep_stack_3->SetBinContent(2,2.384979);
   mass_four_lep_stack_3->SetBinContent(3,5.480469);
   mass_four_lep_stack_3->SetBinContent(4,0.188247);
   mass_four_lep_stack_3->SetBinContent(5,0.02078733);
   mass_four_lep_stack_3->SetBinError(0,0.002840806);
   mass_four_lep_stack_3->SetBinError(1,0.003993413);
   mass_four_lep_stack_3->SetBinError(2,0.01169067);
   mass_four_lep_stack_3->SetBinError(3,0.01780372);
   mass_four_lep_stack_3->SetBinError(4,0.003280131);
   mass_four_lep_stack_3->SetBinError(5,0.0008268347);
   mass_four_lep_stack_3->SetEntries(320579);
   mass_four_lep_stack_3->SetDirectory(0);
   mass_four_lep_stack_3->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   mass_four_lep_stack_3->SetFillColor(ci);
   mass_four_lep_stack_3->SetLineWidth(0);
   mass_four_lep_stack_3->SetMarkerStyle(20);
   mass_four_lep_stack_3->SetMarkerSize(1.2);
   mass_four_lep_stack_3->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   mass_four_lep_stack_3->GetXaxis()->SetLabelFont(42);
   mass_four_lep_stack_3->GetXaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_3->GetXaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_3->GetXaxis()->SetTitleOffset(1.4);
   mass_four_lep_stack_3->GetXaxis()->SetTitleFont(42);
   mass_four_lep_stack_3->GetYaxis()->SetTitle("Events / bin");
   mass_four_lep_stack_3->GetYaxis()->SetLabelFont(42);
   mass_four_lep_stack_3->GetYaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_3->GetYaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_3->GetYaxis()->SetTitleOffset(1.4);
   mass_four_lep_stack_3->GetYaxis()->SetTitleFont(42);
   mass_four_lep_stack_3->GetZaxis()->SetLabelFont(42);
   mass_four_lep_stack_3->GetZaxis()->SetLabelSize(0.05);
   mass_four_lep_stack_3->GetZaxis()->SetTitleSize(0.05);
   mass_four_lep_stack_3->GetZaxis()->SetTitleOffset(1);
   mass_four_lep_stack_3->GetZaxis()->SetTitleFont(42);
   ->Add(mass_four_lep_stack_3,"");
   ->Draw("histsame");
   
   TH1F *mass_four_lep__7 = new TH1F("mass_four_lep__7","Mass of four-lepton system",4,110,135);
   mass_four_lep__7->SetBinContent(0,43.47036);
   mass_four_lep__7->SetBinContent(1,2.265142);
   mass_four_lep__7->SetBinContent(2,7.028155);
   mass_four_lep__7->SetBinContent(3,10.26242);
   mass_four_lep__7->SetBinContent(4,4.227253);
   mass_four_lep__7->SetBinContent(5,255.9081);
   mass_four_lep__7->SetBinError(0,0.5535932);
   mass_four_lep__7->SetBinError(1,0.3437816);
   mass_four_lep__7->SetBinError(2,0.6874597);
   mass_four_lep__7->SetBinError(3,0.6841102);
   mass_four_lep__7->SetBinError(4,0.3831483);
   mass_four_lep__7->SetBinError(5,1.682726);
   mass_four_lep__7->SetEntries(777476);
   mass_four_lep__7->SetDirectory(0);
   mass_four_lep__7->SetStats(0);

   ci = TColor::GetColor("#000099");
   mass_four_lep__7->SetFillColor(ci);
   mass_four_lep__7->SetFillStyle(3454);
   mass_four_lep__7->SetLineColor(0);
   mass_four_lep__7->SetLineWidth(2);
   mass_four_lep__7->SetMarkerStyle(20);
   mass_four_lep__7->SetMarkerSize(0);
   mass_four_lep__7->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   mass_four_lep__7->GetXaxis()->SetLabelFont(42);
   mass_four_lep__7->GetXaxis()->SetLabelSize(0.05);
   mass_four_lep__7->GetXaxis()->SetTitleSize(0.05);
   mass_four_lep__7->GetXaxis()->SetTitleOffset(1.4);
   mass_four_lep__7->GetXaxis()->SetTitleFont(42);
   mass_four_lep__7->GetYaxis()->SetTitle("Events / bin");
   mass_four_lep__7->GetYaxis()->SetLabelFont(42);
   mass_four_lep__7->GetYaxis()->SetLabelSize(0.05);
   mass_four_lep__7->GetYaxis()->SetTitleSize(0.05);
   mass_four_lep__7->GetYaxis()->SetTitleOffset(1.4);
   mass_four_lep__7->GetYaxis()->SetTitleFont(42);
   mass_four_lep__7->GetZaxis()->SetLabelFont(42);
   mass_four_lep__7->GetZaxis()->SetLabelSize(0.05);
   mass_four_lep__7->GetZaxis()->SetTitleSize(0.05);
   mass_four_lep__7->GetZaxis()->SetTitleOffset(1);
   mass_four_lep__7->GetZaxis()->SetTitleFont(42);
   mass_four_lep__7->Draw("e2same");
   
   TH1F *mass_four_lep__8 = new TH1F("mass_four_lep__8","Mass of four-lepton system",4,110,135);
   mass_four_lep__8->SetBinContent(0,42);
   mass_four_lep__8->SetBinContent(1,3);
   mass_four_lep__8->SetBinContent(2,11);
   mass_four_lep__8->SetBinContent(3,12);
   mass_four_lep__8->SetBinContent(4,5);
   mass_four_lep__8->SetBinContent(5,248);
   mass_four_lep__8->SetMinimum(0.1);
   mass_four_lep__8->SetMaximum(35);
   mass_four_lep__8->SetEntries(321);
   mass_four_lep__8->SetDirectory(0);
   mass_four_lep__8->SetStats(0);
   mass_four_lep__8->SetLineWidth(2);
   mass_four_lep__8->SetMarkerStyle(20);
   mass_four_lep__8->SetMarkerSize(1.2);
   mass_four_lep__8->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   mass_four_lep__8->GetXaxis()->SetLabelFont(42);
   mass_four_lep__8->GetXaxis()->SetLabelSize(0);
   mass_four_lep__8->GetXaxis()->SetTitleSize(0);
   mass_four_lep__8->GetXaxis()->SetTitleOffset(1.4);
   mass_four_lep__8->GetXaxis()->SetTitleFont(42);
   mass_four_lep__8->GetYaxis()->SetTitle("Events / bin");
   mass_four_lep__8->GetYaxis()->SetLabelFont(42);
   mass_four_lep__8->GetYaxis()->SetLabelSize(0.05);
   mass_four_lep__8->GetYaxis()->SetTitleSize(0.05);
   mass_four_lep__8->GetYaxis()->SetTitleOffset(1.2);
   mass_four_lep__8->GetYaxis()->SetTitleFont(42);
   mass_four_lep__8->GetZaxis()->SetLabelFont(42);
   mass_four_lep__8->GetZaxis()->SetLabelSize(0.05);
   mass_four_lep__8->GetZaxis()->SetTitleSize(0.05);
   mass_four_lep__8->GetZaxis()->SetTitleOffset(1);
   mass_four_lep__8->GetZaxis()->SetTitleFont(42);
   mass_four_lep__8->Draw("sameE1");
   
   TLegend *leg = new TLegend(0.7,0.5,0.93,0.925,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(32);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("mass_four_lep","Data","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("mass_four_lep_stack_3","Higgs","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("mass_four_lep_stack_2","ZZ","f");

   ci = TColor::GetColor("#33ccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("mass_four_lep_stack_1","Other","f");

   ci = TColor::GetColor("#6666cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("mass_four_lep","Stat. unc.","f");

   ci = TColor::GetColor("#000099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3454);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
      tex = new TLatex(0.18,0.87,"ATLAS Open Data");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.82,"#it{for education}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *mass_four_lep_copy__9 = new TH1F("mass_four_lep_copy__9","Mass of four-lepton system",4,110,135);
   mass_four_lep_copy__9->SetBinContent(0,42);
   mass_four_lep_copy__9->SetBinContent(1,3);
   mass_four_lep_copy__9->SetBinContent(2,11);
   mass_four_lep_copy__9->SetBinContent(3,12);
   mass_four_lep_copy__9->SetBinContent(4,5);
   mass_four_lep_copy__9->SetBinContent(5,248);
   mass_four_lep_copy__9->SetMinimum(0.1);
   mass_four_lep_copy__9->SetMaximum(35);
   mass_four_lep_copy__9->SetEntries(321);
   mass_four_lep_copy__9->SetDirectory(0);
   mass_four_lep_copy__9->SetStats(0);
   mass_four_lep_copy__9->SetLineWidth(2);
   mass_four_lep_copy__9->SetMarkerStyle(20);
   mass_four_lep_copy__9->SetMarkerSize(1.2);
   mass_four_lep_copy__9->GetXaxis()->SetTitle(" m_{4l} [GeV]");
   mass_four_lep_copy__9->GetXaxis()->SetLabelFont(42);
   mass_four_lep_copy__9->GetXaxis()->SetLabelSize(0);
   mass_four_lep_copy__9->GetXaxis()->SetTitleSize(0);
   mass_four_lep_copy__9->GetXaxis()->SetTitleOffset(1.4);
   mass_four_lep_copy__9->GetXaxis()->SetTitleFont(42);
   mass_four_lep_copy__9->GetYaxis()->SetTitle("Events / bin");
   mass_four_lep_copy__9->GetYaxis()->SetLabelFont(42);
   mass_four_lep_copy__9->GetYaxis()->SetLabelSize(0.05);
   mass_four_lep_copy__9->GetYaxis()->SetTitleSize(0.05);
   mass_four_lep_copy__9->GetYaxis()->SetTitleOffset(1.2);
   mass_four_lep_copy__9->GetYaxis()->SetTitleFont(42);
   mass_four_lep_copy__9->GetZaxis()->SetLabelFont(42);
   mass_four_lep_copy__9->GetZaxis()->SetLabelSize(0.05);
   mass_four_lep_copy__9->GetZaxis()->SetTitleSize(0.05);
   mass_four_lep_copy__9->GetZaxis()->SetTitleOffset(1);
   mass_four_lep_copy__9->GetZaxis()->SetTitleFont(42);
   mass_four_lep_copy__9->Draw("sameaxis");
   
   pt = new TPaveText(0.248596,0.9367193,0.751404,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   pt_LaTex = pt->AddText("Mass of four-lepton system");
   pt->Draw();
   pad0->Modified();
   c->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0.08,0.27,0.135,0.29);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(0);
   pad1->SetLeftMargin(0.14);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0);
   pad1->SetBottomMargin(0.5);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0.08,0.132,0.135,0.16);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(0);
   pad1->SetLeftMargin(0.14);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0);
   pad1->SetBottomMargin(0.5);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
